# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '2023.3.16.post1+ge4fd816.d20230316'
__version_tuple__ = version_tuple = (2023, 3, 16, 'ge4fd816.d20230316')
